#!/bin/sh
for i in longmult9.dimacs-iter2000-learn*; do
	echo $i;
	grep -h '^v ' $i |
	while read x; do
		echo LINE;
		( echo $x;
		  cat /home2/versto/Projects/SAT/SATLIB/longmult/BMC-dimacs-examples-0.0/unsatisfiable/longmult9.dimacs | grep -v '^c ' | grep -v '^p '
		) | awk -f awk-script  | grep 'res 0';
	done;
done
